version: '3.1'
services :
  db:
    container_name: postgres-cont
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  admin:
    container_name: adminer-cont
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080